node test/unexpected-op.js &&
node test/fill-up.js &&
node test/fill-up-empty.js &&
node test/recover-stake.js &&
node test/deposit-validator-ok.js &&
node test/deposit-validator-ok2.js &&
node test/deposit-validator-not-validator.js &&
node test/deposit-validator-zero.js &&
node test/withdraw-validator-ok.js &&
node test/withdraw-validator-ok2.js &&
node test/withdraw-validator-error.js &&
node test/withdraw-validator-error2.js &&
node test/new-stake-ok.js &&
node test/new-stake-has-withdraws.js &&
node test/new-stake-state.js &&
node test/new-stake-validator-amount.js &&
node test/new-stake-error.js &&
node test/deposit-nominator-ok.js &&
node test/deposit-nominator-ok-pending.js &&
node test/deposit-nominator-ok-new.js &&
node test/deposit-nominator-ok-pending-new.js &&
node test/deposit-nominator-amount.js &&
node test/deposit-nominator-max.js &&
node test/deposit-nominator-min-deposit.js &&
node test/withdraw-nominator-ok.js &&
node test/withdraw-nominator-ok2.js &&
node test/withdraw-nominator-ok-pending.js &&
node test/withdraw-nominator-not-found.js &&
node test/withdraw-nominator-error.js &&
node test/withdraw-request-ok.js &&
node test/withdraw-request-ok2.js &&
node test/withdraw-request-not-found.js &&
node test/withdraw-request-error.js &&
node test/withdraw-requests-ok.js &&
node test/withdraw-requests-limit.js &&
node test/withdraw-requests-balance.js &&
node test/elector-error.js &&
node test/elector-ok.js &&
node test/elector.js &&
node test/votes-create-ok.js &&
node test/votes-create-denied.js &&
node test/votes-ok.js &&
node test/votes-clean.js &&
echo "OK"